version: '3'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./saved_models:/app/saved_models
      - ./config:/app/config
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
