# Model Prediction Parameters

# XGBoost model parameters (optimized through Optuna)
model_params:
  learning_rate: 0.03
  n_estimators: 250
  max_depth: 12
  min_child_weight: 4
  gamma: 0.1
  subsample: 0.85
  colsample_bytree: 0.8
  reg_alpha: 0.1
  reg_lambda: 0.1
  random_state: 42

# Prediction threshold (set to 0.001 for high sensitivity)
prediction_threshold: 0.001

# Alternative thresholds for different use cases
# - High sensitivity (catch all potential cases): 0.001
# - Balanced (default): 0.5
# - High specificity (minimize false positives): 0.7

# Feature importance (top 25 features)
important_features:
  # Top 16 features from cross-validation
  - FS
  - NYHA
  - Chest_pain
  - LVIDs
  - DT
  - Wall_Subendocardial
  - LAV
  - HR
  - BNP
  - ECG_T_inversion
  - Age
  - BMI
  - EA
  - LDLc
  - ICT
  - RBS
  # Additional features to reach 25
  - LVEF
  - Sex
  - HTN
  - DM
  - Smoker
  - DL
  - TropI
  - RWMA
  - MR

# Performance metrics from cross-validation
performance_metrics:
  accuracy: 0.86
  precision: 0.87
  recall: 0.81
  f1_score: 0.83
  roc_auc: 0.94

# Data preprocessing parameters
preprocessing:
  drop_columns:
    - StudyID
  categorical_columns:
    - NYHA
    - Wall_Subendocardial
    - ECG_T_inversion
    - Chest_pain
    - Sex
    - HTN
    - DM
    - Smoker
    - DL
    - RWMA
    - MR
  numerical_columns:
    - Age
    - BMI
    - HR
    - RBS
    - FS
    - LVIDs
    - LAV
    - ICT
    - EA
    - DT
    - LDLc
    - BNP
    - LVEF
    - TropI
