columns:
  - Age: float
  - Sex: category
  - BMI: float
  - NYHA: category
  - HR: float
  - HTN: category
  - DM: category
  - Smoker: category
  - DL: category
  - BA: category
  - RBS: float
  - HbA1C: float
  - Creatinine: float
  - Na: float
  - K: float
  - Cl: float
  - Hb: float
  - TropI: float
  - CXR: category
  - ECG: category
  - LVIDd: float
  - FS: float
  - LVIDs: float
  - LVEF: float
  - RWMA: category
  - LAV: float
  - MI: category
  - ACS: category
  - Wall: category
  - Thrombolysis: category
  - ICT: float
  - IRT: float
  - MR: int
  - EA: float
  - DT: float
  - MPI: float
  - RR: float
  - Chest_pain: category
  - TC: float
  - LDLc: float
  - HDLc: float
  - TG: float
  - BNP: float
  - HF: category

numerical_columns:
  - Age
  - BMI
  - HR
  - RBS
  - HbA1C
  - Creatinine
  - Na
  - K
  - Cl
  - Hb
  - TropI
  - LVIDd
  - FS
  - LVIDs
  - LVEF
  - LAV
  - ICT
  - IRT
  - MR
  - EA
  - DT
  - MPI
  - RR
  - TC
  - LDLc
  - HDLc
  - TG
  - BNP

categorical_columns:
  - Sex
  - NYHA
  - HTN
  - DM
  - Smoker
  - DL
  - BA
  - CXR
  - ECG
  - RWMA
  - MI
  - ACS
  - Wall
  - Thrombolysis
  - Chest_pain
  - HF


drop_columns:
  - StudyID


# for data transformation
num_features:
  - Age
  - BMI
  - HR
  - RBS
  - HbA1C
  - Creatinine
  - Na
  - K
  - Cl
  - Hb
  - TropI
  - LVIDd
  - FS
  - LVIDs
  - LVEF
  - LAV
  - ICT
  - IRT
  - MR
  - EA
  - DT
  - MPI
  - RR
  - TC
  - LDLc
  - HDLc
  - TG
  - BNP

or_columns:
  - Sex
  - NYHA
  - HTN
  - DM
  - Smoker
  - DL
  - BA
  - CXR
  - RWMA
  - MI
  - Chest_pain
  - HF


oh_columns:
  - ECG
  - ACS
  - Wall
  - Thrombolysis
  - MR

transform_columns:
  log_transform:
    - BMI
    - HR
    - RBS
    - Creatinine
    - K
    - LVIDs
    - MR
    - MPI
    - RR
    - TC
    - LDLc
    - HDLc
    - TG

  sqrt_transform:
    - HbA1C
    - Cl
    - TropI
    - BNP

  boxcox_transform:
    - Na
    - K
    - Hb
    - LVIDd
    - FS
    - LVEF
    - LAV
    - IRT
    - EA
    - DT
    - RR
